baseURL = "https://itsaakashgupta.github.io/"
languageCode = "en-us"
title = "Akash Gupta| Data Analyst"
_enabled_editors = ["visual", "content"]

[taxonomies]
category = 'categories'
tag = 'tags'

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'