# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Preview
  description: Shows a truncated preview of the About page with a View all link
  icon: person
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  title: "About me"
  char_limit: 400
  link_label: "View all"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}

