# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Page Heading
  description: Generic page heading
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  description: ""
  demo_url: ""
  repo_url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: My works
  description: I show only my best works built completely with passion,
    simplicity, and creativity!
  demo_url: https://example.com
  repo_url: https://github.com/example/repo

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
